# -*- coding: utf-8 -*-


import re

#This script was built automatically, using the script: "make_md_template_SA.py"

with open("reference_file.md", "w") as f_new:
	f_new.write('#Dynamic Name Server Black List\n')
	f_new.write('\n')
	f_new.write('## Summary\n')
	f_new.write('DNS Blacklists are often specifically focused on combating spam. They allow a website admin to block mail from systems that have been identified as spammers. The list converts IP addresses to domain names so that they can be easily read, searched, and used. If the maintainer of a DNS blacklist has been previously sent spam from any domain, it\'s server would be "blacklisted" and all messages sent from it would be either flagged or rejected from all sites that use that specific list.\n')
	f_new.write('\n')
	f_new.write('\n')
	f_new.write('## Description\n')
	f_new.write('This data set includes information generated from Dynamic Name Server Blacklists.\n')
	f_new.write('\n')
	f_new.write('A DNS-based Blackhole List (DNSBL) or Real-time Blackhole List (RBL), functions as an effort to stop email spamming, and it consists of a "blacklist" of locations on the Internet reputed to send email spam. These locations are the IP addresses which are most frequently used to publish the addresses of computers or networks linked to spamming. These lists in turn can be used for "flagging" messages sent from a particular site, listed on one or more of such lists.\n')
	f_new.write('\n')
	f_new.write('Complementing the IP list are Boolean values indicating whether or not a Malware Type is published via a particular IP or not. These DNSBLs may include addresses of zombie computers or other machines being used to send spam, ISPs who willingly host spammers, or those which have sent spam to a honeypot system.\n')
	f_new.write('\n')
	f_new.write('This data has been generated using the above mentioned Dynamic Name Server Blacklists, from which ip addresses and domains have been scraped, as well as any other available information. The output has in turn been enriched by WhoIs information, obtained by querying data from one of the Regional Internet Registries, for each ip/domain: \n')
	f_new.write('\n')
	f_new.write('(1) American Registry for Internet Numbers—ARIN: Responsible for the administration of Internet addresses and domains for North America, including Canada, the United States and portions of the Caribbean.\n')
	f_new.write('(2) Rseaux IP Europens Network Coordination Centre—RIPE NCC: Responsible for the administration of Internet addresses and domains for Europe, the Middle East and Central Asia. RIPE NCC is considered the first official registry—the United States government was still too busy being actively involved with managing Internet addressing for much of North America \n')
	f_new.write('at that time, and therefore was not first.\n')
	f_new.write('(3) The Asia-Pacific Network Information Centre—APNIC: Responsible for the administration of Internet addresses and domains for Asia and the Pacific Rim. Founded in Tokyo, Japan, APNIC was the second RIR to be established. APNIC relocated to Brisbane, \n')
	f_new.write('Australia, in 1998.\n')
	f_new.write('(4) Latin American and Caribbean Internet Address Registry—LACNIC: Responsible for the administration of Internet addresses and domains for Latin America and the Caribbean. Headquartered in Montevideo, Uruguay.\n')
	f_new.write('(5) The African Network Information Centre—AfriNIC: Responsible for the administration of Internet addresses and domains for the African continent. Based in Ebene City, Mauritius, AfriNIC became operational in 2005.\n')
	f_new.write('\n')
	f_new.write('\n')
	f_new.write('## Facts\n')
	f_new.write('- Date Created: 2016-02-10\n')
	f_new.write('- Date Modified: 2016-03-06\n')
	f_new.write('- Version: 2016.2\n')
	f_new.write('- Update Frequency: 72 hours\n')
	f_new.write('- Temporal Coverage: 2016-02\n')
	f_new.write('- Spatial Coverage: N/A\n')
	f_new.write('- Sources:  Black Lists\n')
	f_new.write('- Source URL: -\n')
	f_new.write('- Source License Requirements: None\n')
	f_new.write('- Source Citation: BLACKLIST_DNS_OUTPUT.csv\n')
	f_new.write('- Keywords: \n')
	f_new.write('  - Google Safe Browsing List\n')
	f_new.write('  - Malware Blacklists\n')
	f_new.write('  - Phishing Blacklists\n')
	f_new.write('  - Spam Blacklists\n')
	f_new.write('  - DNS Blacklists\n')
	f_new.write('  - RBL\n')
	f_new.write('  - DNSBL\n')
	f_new.write('  - URI DNSBL\n')
	f_new.write('- Other Titles and Uses: \n')
	f_new.write('  - Zone Field Analysis\n')
	f_new.write('  - ISP_Enrichment\n')
	f_new.write('\n')
	f_new.write('\n')
	f_new.write('\n')
	f_new.write('## Schema\n')
	f_new.write('- Data_Upload_ID_Text\n')
	f_new.write('  - Type: String\n')
	f_new.write('\n')
	f_new.write('- Universally_Unique_Identifier_Text\n')
	f_new.write('  - A universally unique identifier (UUID) is an identifier standard used in software construction. A UUID consists of a 128-bit value. A UUID is formatted according to a specified variant and a specific version of the variant, and the meaning of each bit is defined by any of several variants.\n')
	f_new.write('  - Type: String\n')
	f_new.write('\n')
	f_new.write('- Referential_Text\n')
	f_new.write('  - Type: String\n')
	f_new.write('\n')
	f_new.write('- Data_Source_Name\n')
	f_new.write('  - This is always "jsl"\n')
	f_new.write('  - Type: String\n')
	f_new.write('\n')
	f_new.write('- Date\n')
	f_new.write('  - Date of first uptime\n')
	f_new.write('  - Type: Date \n')
	f_new.write('\n')
	f_new.write('- Cog\n')
	f_new.write('\n')
	f_new.write('- Model\n')
	f_new.write('\n')
	f_new.write('- Concept\n')
	f_new.write('\n')
	f_new.write('- Segment\n')
	f_new.write('\n')
	f_new.write('- Pedigree_Number\n')
	f_new.write('  - Quality/integrity of data source\n')
	f_new.write('  - Type: Number\n')
	f_new.write('\n')
	f_new.write('- Confidence_Score_Number\n')
	f_new.write('  - Number between 1 and 10 which defines the reliability of the data\n')
	f_new.write('  - Type: Integer\n')
	f_new.write('  - Required\n')
	f_new.write('\n')
	f_new.write('- IP_Address_Text\n')
	f_new.write('  - IP address corresponding to entry on blacklist\n')
	f_new.write('  - Type: String\n')
	f_new.write('  - Required\n')
	f_new.write('\n')
	f_new.write('- IP_Address_Integer\n')
	f_new.write('  - IP address represented in integer notation. An IP address in string form can be converted to integer form by breaking it into four octets. We then perform a calculation on these. For example, given the IP address 213.122.92.232, we have:\n')
	f_new.write('    - First Octet:  213\n')
	f_new.write('    - Second Octet: 122\n')
	f_new.write('    - Third Octet:  92\n')
	f_new.write('    - Fourth Octet: 232\n')
	f_new.write('\n')
	f_new.write('  And then we can perform the calculation as follows:\n')
	f_new.write('\n')
	f_new.write('  (first octet * 256³) + (second octet * 256²) + (third octet * 256) + (fourth octet)\n')
	f_new.write('\n')
	f_new.write('  = (first octet * 16777216) + (second octet * 65536) + (third octet * 256) + (fourth octet)\n')
	f_new.write('\n')
	f_new.write('  = (213 * 16777216) + (122 * 65536) + (92 * 256) + (232)\n')
	f_new.write('  \n')
	f_new.write('  = 3581566184.\n')
	f_new.write('  - Type: Integer\n')
	f_new.write('  - Required\n')
	f_new.write('\n')
	f_new.write('- Offender_Class_Text\n')
	f_new.write('  - The offender class determines the type of blacklist. The offender class for this dataset is "dns_bl".\n')
	f_new.write('  - Type: String\n')
	f_new.write('  - Required\n')
	f_new.write('\n')
	f_new.write('- First_Observed_date\n')
	f_new.write('  - Date corresponding to the first time the item was observed.\n')
	f_new.write('  - Type: Date\n')
	f_new.write('  - Required\n')
	f_new.write('\n')
	f_new.write('- First_Observed_time\n')
	f_new.write('  - Time corresponding to the first time the item was observed\n')
	f_new.write('  - Type: Time\n')
	f_new.write('  - Required\n')
	f_new.write('\n')
	f_new.write('- Most_Recent_Observation_date\n')
	f_new.write('  - Date corresponding to most recent observation of entry.\n')
	f_new.write('  - Type: Date\n')
	f_new.write('  - Required\n')
	f_new.write('\n')
	f_new.write('- Most_Recent_Observation_time\n')
	f_new.write('  - Time corresponding to most recent observation of entry.\n')
	f_new.write('  - Type: Time\n')
	f_new.write('  - Required\n')
	f_new.write('\n')
	f_new.write('- Total_Observations_Integer\n')
	f_new.write('  - Total number of times entry has been observed.\n')
	f_new.write('  - Type: Integer\n')
	f_new.write('  - Required\n')
	f_new.write('\n')
	f_new.write('- Blacklist_Ranking_Integer\n')
	f_new.write('  - Ranking correspinding to blacklist/item in blacklist. \n')
	f_new.write('  - Type: Integer\n')
	f_new.write('\n')
	f_new.write('- Threat_Score_Integer\n')
	f_new.write('  - Type: Integer\n')
	f_new.write('\n')
	f_new.write('- Total_Capabilities_Integer\n')
	f_new.write('  - Type: Integer\n')
	f_new.write('\n')
	f_new.write('- Commvett \n')
	f_new.write('\n')
	f_new.write('- Commdatevett\n')
	f_new.write('\n')
	f_new.write('- Govvett\n')
	f_new.write('\n')
	f_new.write('- Govdatevett\n')
	f_new.write('\n')
	f_new.write('- Country_Abbreviation_Text\n')
	f_new.write('  - Two letter country code.\n')
	f_new.write('  - Type: String\n')
	f_new.write('\n')
	f_new.write('- Country_Text\n')
	f_new.write('  - Country corresponding to listed item.\n')
	f_new.write('  - Type: String\n')
	f_new.write('\n')
	f_new.write('- City_Name\n')
	f_new.write('  - City corresponding to location of IP address/domain of blacklist entry.\n')
	f_new.write('  - Type: String\n')
	f_new.write('\n')
	f_new.write('- Coordinates_Number\n')
	f_new.write('  - Coordinates corresponding to loaction of IP address/domain od blacklist entry.\n')
	f_new.write('  - Type: Location\n')
	f_new.write('  - Format: GeoPoint\n')
	f_new.write('\n')
	f_new.write('- Geographic_Longitude\n')
	f_new.write('  - Geographic longitude corresponding to location of IP address/domain on entry.\n')
	f_new.write('  - Type: Location\n')
	f_new.write('\n')
	f_new.write('- Geographic_Latitude\n')
	f_new.write('  - Geographic latitude corresponding to location of IP address/domain on entry.\n')
	f_new.write('  - Type: Location\n')
	f_new.write('\n')
	f_new.write('- ISP_Text\n')
	f_new.write('  - An Internet service provider (ISP) is an organization that provides services for accessing and using the Internet. Internet services typically provided by ISPs, include Internet access, Internet transit, domain name registration, web hosting, Usenet service, and colocation. They may be commercial, community-owned, non-profit, or otherwise privately owned. Classifications include the following:\n')
	f_new.write('  \n')
	f_new.write('    - Access providers ISP\n')
	f_new.write('    - Edge providers\n')
	f_new.write('    - Mailbox providers\n')
	f_new.write('    - Hosting ISPs\n')
	f_new.write('    - Transit ISPs\n')
	f_new.write('    - Virtual ISPs\n')
	f_new.write('    - Free ISPs\n')
	f_new.write('    - Wireless ISP\n')
	f_new.write('  - Type: String\n')
	f_new.write('\n')
	f_new.write('- Domain_Name\n')
	f_new.write('  - Domain name of an entry in the blacklist.\n')
	f_new.write('  - Type: String\n')
	f_new.write('\n')
	f_new.write('- Network_Speed_Number\n')
	f_new.write('  - Network speed corresponding to entry in dataset.\n')
	f_new.write('  - Type: Number\n')
	f_new.write('\n')
	f_new.write('- Network_Autonomous_System_Number\n')
	f_new.write('  - An autonomous system number (ASN) is a unique number that\'s available globally to identify an autonomous system and which enables that system to exchange exterior routing information with other neighboring autonomous systems. \n')
	f_new.write('  The number of autonomous system numbers is limited. For autonomous system numbers to be assigned, current guidelines need the network to be multi-homed and have a unique routing policy. Autonomous system numbers can be assigned only through a request to the local Internet registry.\n')
	f_new.write('  - Type: Integer\n')
	f_new.write('\n')
	f_new.write('- Network_Class\n')
	f_new.write('  - This could be one of five IP network classes: A, B, C, D or E. Network addressing architecture divides the address space into these five classes. Each class defines either a network size for the number of hosts for unicast addresses (classes A, B, C), or a multicast network (class D). The fifth class (E) is reserved for future or experimental purposes.\n')
	f_new.write('\n')
	f_new.write('    - Class A: Class A addresses are IP addresses that are assigned to network devices, such as computers, and include all addresses in which the first bit of the first octet is set to 0 (zero). This includes all values from 00000001 to 01111111, or 1 to 127.\n')
	f_new.write('\n')
	f_new.write('    - Class B: Class B addresses are IP addresses that are assigned to network devices, such as computers, and include all addresses in which the first two bits of the first octet are 10. This includes all values from 10000000 to 10111111, or 128 to 191.\n')
	f_new.write('    \n')
	f_new.write('\n')
	f_new.write('    - Class C: Class C addresses are IP addresses that are assigned to network devices, such as computers, and include all addresses in which the first three bits of the first octet are set to 110. This includes all values from 11000000 to 11011111, or 192 to 223.\n')
	f_new.write('\n')
	f_new.write('    - Class D: Class D network addresses are not assigned to devices on a network. These addresses are used for special-purpose, multicast applications (such as video- and audio-streaming applications). These addresses all need to be registered with IANA to be used globally. Addresses in this class have the first bits of the first octet set to 1110, yielding addresses in the first octet ranging from 11100000 to 11101111, or 224 to 239. These addresses are not defined by a normal subnet mask; instead, each address is used for a specific purpose. And because each address is individually used, it uses a 255.255.255.255 mask.\n')
	f_new.write('\n')
	f_new.write('    - Class E: If Class D is special, Class E addresses are even more special. There is no defined use for this address class. Officially, it is listed as reserved for usage and testing by IANA and the Internet Research Task Force (IRTF). In fact, as of RFC3330 in 2002, Class E was updated to “reserved for future use.” Class E comprises absolutely all valid addresses with 240 or higher in the first octet. The first bits of the first octet is 1111, which yields addresses from 11110000 to 11111110 — or technically, 11111111 — which, in decimals, are 240 to 254 — or 255.\n')
	f_new.write('  - Type: String\n')
	f_new.write('\n')
	f_new.write('- Network_Type_Text\n')
	f_new.write('  - This could be one of the following types: LAN, WAN, WLAN, MAN, SAN, PAN, EPN or VPN. \n')
	f_new.write('  The "network type" defines the type of computer network involved,and it can characterise the size as well as the purpose of the network. The size of a network can be expressed by the geographic area it occupies and the number of computers    which form the network. It could comprise of a few devices occupying a single room, or millions of devices spread across  the entire globe. Examples of networks based on size are:\n')
	f_new.write('    - Personal area network, or PAN\n')
	f_new.write('    - Local area network, or LAN\n')
	f_new.write('    - Metropolitan area network, or MAN\n')
	f_new.write('    - Wide area network, or WAN\n')
	f_new.write('\n')
	f_new.write('    In terms of purpose, many networks can be considered general purpose, which means they are used for everything from sending files to a printer to accessing the Internet. Some types of networks, however, serve a very particular purpose.Some of the different networks based on their main purpose are:\n')
	f_new.write('    - Storage area network, or SAN\n')
	f_new.write('    - Enterprise private network, or EPN\n')
	f_new.write('    - Virtual private network, or VPN\n')
	f_new.write('    \n')
	f_new.write('  - Type: String\n')
	f_new.write('\n')
	f_new.write('- is_Active\n')
	f_new.write('  - Determines whether IP/domain in list is active or not.\n')
	f_new.write('  - Type: Boolean\n')
	f_new.write('\n')
	f_new.write('- Insrtdttm\n')
	f_new.write('\n')
	f_new.write('- Updtdttm\n')
	f_new.write('\n')
	f_new.write('\n')
